project/blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
from site_setup.views import site_config

app_name = 'blog'

urlpatterns = [

    path('', views.index, name="index"),
    path('admin_dashboard/', views.admin_dashboard, name="admin_dashboard"),

    path('site_config', site_config, name="site_config"),

    path('users/', views.users_views, name="users"),
    path('create_user/', views.create_user, name="create_user"),
    path('edit_user/<int:user_id>/', views.edit_user, name="edit_user"),
    path('change_password/<int:user_id>/', views.change_password, name="change_password"),
    path('user_active/<int:user_id>/', views.user_active, name="user_active"),
    path('user_staff/<int:user_id>/', views.user_staff, name="user_staff"),
    path('delete_user/<int:user_id>/', views.delete_user, name="delete_user"),

    path('news/', views.news, name="news"),
    path('new/<slug:slug>/', views.new, name="new"),
    path('add_news/', views.add_news, name="add_news"),
    path('edit_news/<int:id>/', views.edit_news, name="edit_news"),
    path('delete_news/<int:id>/', views.delete_news, name="delete_news"), # type: ignore
    path('delete_image_news/<int:id>/', views.delete_image_news, name="delete_image_news"),
    path('news_published/<int:id>/', views.news_published, name="news_published"),

    path('events/', views.events, name='events'),
    path('event/<slug:slug>/', views.event, name="event"),
    path('add_event/', views.add_event, name="add_event"),
    path('edit_event/<int:id>/', views.edit_event, name="edit_event"),
    path('delete_event/<int:id>/', views.delete_event, name="delete_event"),
    path('delete_image_event/<int:id>/', views.delete_image_event, name="delete_image_event"),
    path('event_published/<int:id>/', views.event_published, name="event_published"),

    path('page/<slug:slug>/', views.page, name="page"),

    path('search/', views.search, name='search'),

    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    
    path('post/<slug:slug>/', views.post, name="post"), 
    path('category/<slug:slug>/', views.category, name="category"),
    path('tag/<slug:slug>/', views.tag, name="tag"),
    path('shops/', views.shops, name='shops'),
    # path('shops/', views.ShopsViews.as_view(), name='shops'),
    path('admin_shops/', views.admin_shops, name='admin_shops'),
    path('new_post/', views.new_post, name='new_post'),
    path('edit_post/<int:id>/', views.edit_post, name="edit_post"),
    path('delete_post/<int:id>/', views.delete_post, name="delete_post"),
    path('delete_image_post/<int:id>/', views.delete_image_post, name="delete_image_post"),
    path('shop_published/<int:id>/', views.shop_published, name="shop_published"),
    path('new_category/', views.new_category, name='new_category'),
    path('new_tag/', views.new_tag, name='new_tag'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('delete_tag/<int:tag_id>/', views.delete_tag, name='delete_tag'),

    path('newsletters/', views.subs, name="newsletters"),
    path('newsletter/', views.newsletter, name="newsletter"), # type: ignore
    path('delete_newsletter/<int:newsletter_id>/', views.delete_newsletter, name="delete_newsletter"),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/blog/views/_users_views.py
from django.shortcuts import render
from django.contrib.auth.models import User

def users_views(request):
    users = User.objects.order_by('first_name')

    context = {
        'users': users,
    }

    return render(request, 'blog/pages/users.html', context)

project/blog/views/admin_views.py
from django.shortcuts import render, redirect
from blog.models import User, CommentsEvents, CommentsNews, NewsLetter

def admin_dashboard(request):
    new_users = User.objects.order_by('-id')[:5]
    new_comments = CommentsNews.objects.order_by('-created_at')[:5]
    event_comments = CommentsEvents.objects.order_by('-created_at')[:5]
    news_letters = NewsLetter.objects.order_by('-id')[:5]

    context = {
        'new_users': new_users,
        'new_comments': new_comments,
        'event_comments': event_comments,
        'news_letters': news_letters,
    }

    return render(request, 'blog/partials/_main_dashboard.html', context)

project/blog/views/category_view.py
from django.shortcuts import render
from blog.models import Post
from django.core.paginator import Paginator

PER_PAGE = 9

def category(request, slug):
    shops = Post.objects.get_published().filter(category__slug=slug).order_by('id') # type: ignore
    
    if shops:
        for i in shops:
            category = f'{i.category.name} - '
    else:
        category = ''

    paginator = Paginator(shops, PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'shops': page_obj,
        'page_title': category,
    }

    return render(request, 'blog/pages/shops.html', context)

project/blog/views/change_password_view.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from blog.forms import CustomPasswordChangeForm
from django.contrib.auth.decorators import login_required

def is_admin(user):
    return user.is_superuser

@login_required
def change_password(request, user_id):

    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        form = CustomPasswordChangeForm(user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Senha atualizada com sucesso!')
            return redirect('blog:change_password', user_id=user_id)
        else:
            print(form.errors)
            messages.error(request, 'Algo deu errado ao alterar sua senha, verifique os campos e tente novamente.')
    else:
        form = CustomPasswordChangeForm(user)

    context = {
        'form': form,
    }

    return render(request, 'blog/pages/change_password.html', context)

project/blog/views/create_user_view.py
from django.shortcuts import render, redirect
from django.contrib import messages
from blog.forms import CustomUserCreationForm, ProfileUpdateForm
from blog.models import Profile
from django.contrib.auth.decorators import login_required, user_passes_test

def is_admin(user):
    return user.is_superuser

def create_user(request):

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        form_image = ProfileUpdateForm(request.POST, request.FILES)

        if form.is_valid():
            new_user = form.save()

            if form_image.is_valid():
                image = request.FILES.get('profile_image')
                Profile.objects.create(user=new_user, profile_image=image)
                messages.success(request, 'Imagem de perfil salva com sucesso')

            messages.success(request, 'Usuário criado com sucesso!')
            return redirect('blog:index')
        else:
            messages.error(request, 'Algo deu errado, verifique os campos necessários!')

    else:
        form = CustomUserCreationForm()
        form_image = ProfileUpdateForm()

    context = {
        'form': form,
        'form_image': form_image,
    }

    return render(request, 'blog/pages/create_user.html', context)

project/blog/views/edit_user_view.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from blog.forms import CustomUserChangeForm, ProfileUpdateForm
from blog.models import Profile
from django.contrib.auth.decorators import login_required, user_passes_test

def is_admin(user):
    return user.is_superuser

@login_required
def edit_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    profile, created = Profile.objects.get_or_create(user=user)

    form = CustomUserChangeForm(instance=user)
    form_image = ProfileUpdateForm(instance=profile)


    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)
        form_image = ProfileUpdateForm(request.POST, request.FILES, instance=profile)

        # if form.is_valid():
        #     new_user = form.save()

        #     if form_image.is_valid():
        #         new_user.profile_image.profile_image.delete()
        #         image_instance = request.FILES.get('profile_image')
        #         Profile.objects.create(user=new_user, profile_image=image_instance)

            # if form_image.is_valid():
                # image_instance = form_image.save(commit=False)
                # image_instance.user = new_user
                # print(image_instance.user)
                # image_instance.save()

                # if image_instance:
                # messages.success(request, 'Imagem atualizada com sucesso!')

        if form.is_valid() and form_image.is_valid():
            form.save()
            form_image.save()

            if form_image:
                messages.success(request, 'Imagem atualizada com sucesso!')

            messages.success(request, 'Usuário atualizado com sucesso!')
            return redirect('blog:edit_user', user_id=user_id)
        else:
            messages.error(request, 'Algo deu errado ao atualizar seus dados, verifique os campos novamente.')        

    context = {
        'profile': user,
        'form': form,
        'form_image': form_image,
    }

    return render(request, 'blog/pages/edit_user.html', context)

def user_active(request, user_id):
    activated = User.objects.get(id=user_id)

    if request.POST.get('is_active') == 'on':
        activated.is_active = True
        activated.save()
        messages.success(request, 'Usúário ativado')
        return redirect('blog:users')
    else:
        activated.is_active = False
        activated.save()
        messages.error(request, 'Usuário desativado')
        return redirect('blog:users')
    
def user_staff(request, user_id):
    activated = User.objects.get(id=user_id)

    if request.POST.get('is_staff') == 'on':
        activated.is_staff = True
        activated.save()
        messages.success(request, 'Usúário com acesso administrativo')
        return redirect('blog:users')
    else:
        activated.is_staff = False
        activated.save()
        messages.error(request, 'Usuário sem acesso administrativo')
        return redirect('blog:users')
    
def delete_user(request, user_id):
    target = User.objects.get(id=user_id)

    if target:
        target.delete()
        messages.success(request, 'Usuário deletado com sucesso.')
        
    return redirect('blog:users')

project/blog/views/event_view.py
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import Events, ImageEvent
from blog.forms import CommentsEventsForm, AddEventsForm, EditEventsForm, AddImagesEventsForm
from django.core.paginator import Paginator
from django.contrib import messages

PER_PAGE = 5
PER_PAGE_ADMIN = 20

def event(request, slug):
    event = Events.objects.get(slug=slug)
    comments = event.comments.all().order_by('-created_at') #type:ignore
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentsEventsForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.event = event
            new_comment.author = request.user
            new_comment.save()
            return redirect('blog:event', slug=event.slug)
    else:
        comment_form = CommentsEventsForm()

        paginator = Paginator(comments, PER_PAGE) # type: ignore
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
       
    context = {
        'event': event,
        'page_title': f'{event.title} - ',
        'page_obj': page_obj,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
    }

    return render(request, 'blog/pages/event.html', context)

def events(request):
    events = Events.objects.order_by('-created_at')

    paginator = Paginator(events, PER_PAGE_ADMIN) # type: ignore
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
       
    context = {
        'page_obj': page_obj,
    }

    return render(request, 'blog/pages/events.html', context)

def add_event(request):
    form = AddEventsForm()
    form_images = AddImagesEventsForm()

    if request.method == 'POST':
        form = AddEventsForm(request.POST, request.FILES)
        form_images = AddImagesEventsForm(request.POST, request.FILES)

        if form.is_valid():
            event_ = form.save()

            if form_images.is_valid():
                i = 0 
                images = request.FILES.getlist('image')
                for file in images:
                    ImageEvent.objects.create(event=event_, image=file)
                    i += 1
                messages.warning(request, f'{i} imagens salvas com sucesso')
            messages.success(request, 'Evento salvo com sucesso')
            return redirect('blog:events')

    context = {
        'form': form,
        'form_images': form_images,
    }

    return render(request, 'blog/pages/add_events.html', context)


def edit_event(request, id):
    event_ = Events.objects.get(id=id)
    form = EditEventsForm(instance=event_)
    form_images = AddImagesEventsForm(instance=event_)

    if request.method == 'POST':
        form = EditEventsForm(request.POST, request.FILES, instance=event_)
        form_images = AddImagesEventsForm(request.POST, request.FILES, instance=event_)

        if form.is_valid():
            new_event = form.save()

            if form_images.is_valid():
                i = 0
                images = request.FILES.getlist('image')
                for file in images:
                    ImageEvent.objects.create(event=new_event, image=file)
                    i += 1
                messages.warning(request, f'{i} imagens salvas.')
            messages.success(request, 'Evento atualizado com sucesso.')
            return redirect('blog:edit_event', id=id)

    context = {
        'events': event_,
        'form': form,
        'form_images': form_images,
    }

    return render(request, 'blog/pages/edit_events.html', context)


def delete_event(request, id):
    event_ = get_object_or_404(Events, id=id)
    if event_:
        event_.delete()
        messages.success(request, 'Evento excluído com sucesso.')
    return redirect('blog:events')

def delete_image_event(request, id):
    image = ImageEvent.objects.get(id=id)
    event_id = image.event.id #type:ignore
    if image:
        image.delete()
    return redirect('blog:edit_event', id=event_id)

def event_published(request, id):
    event_ = Events.objects.get(id=id)
    if request.POST.get('is_published') == 'on':
        event_.is_published = True
        event_.save()
        messages.success(request, 'Evento publicado.')
    else:
        event_.is_published = False
        event_.save()
        messages.warning(request, 'Evento despublicado')

    return redirect('blog:events')

project/blog/views/index_views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from blog.models import Post, News, Events
from django.db.models import Count

PER_PAGE = 9


def index(request):
    shops = Post.objects.get_published().order_by('-id') # type: ignore
    news = News.objects.get_published().annotate(num_comments=Count('comments')).order_by('-created_at')[:3] # type: ignore
    events = Events.objects.get_published().annotate(num_comments=Count('comments')).order_by('-created_at')[:3] # type: ignore

    paginator = Paginator(shops, PER_PAGE) # type: ignore
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'shops': page_obj,
        'news': news,
        'events': events,
    }

    return render(request, 'blog/pages/index.html', context)

project/blog/views/login_logout_view.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from blog.forms import LoginForm

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Login efetuado com sucesso, bem vindo!')
                return redirect('blog:index')
            else:
                messages.error(request, 'Usuário ou senha inválidos')
    
    form = LoginForm()

    context = {
        'form': form,
    }

    return render(request, 'blog/pages/login.html', context)

def logout_user(request):
    logout(request)
    messages.success(request, 'Saiu da sua conta!')
    return redirect('blog:index')

project/blog/templates/blog/pages/edit_events.html
{% extends "blog/pages/admin_dashboard.html" %}
{% block admin_content %}
    <div class="conatiner container-width mx-auto">
        <form class="row" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-check mb-3">
                {{form.is_published.label_tag}}
                {{form.is_published}}
                <p>{% if form.is_published.help_text %}{{form.is_published.help_text}}{% endif %}</p>
            </div>
            
            <div class="col-12 mb-3">
                {{form.title.label_tag}}
                {{form.title}}
                <p>{% if form.title.help_text %}{{form.title.help_text}}{% endif %}</p>
                {% if form.title.errors %}
                    {% for error in form.title.errors %}
                        <div class="alert alert-danger">
                            {{error}}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="col-12 mb-3">
                {{form.short_description.label_tag}}
                {{form.short_description}}
                <p>
                    {% if form.short_description.help_text %}
                    {{form.short_description.help_text}}
                    {% endif %}
                </p>
                {% if form.short_description.errors %}
                    {% for error in form.short_description.errors %}
                        <div class="alert alert-danger">
                            {{error}}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="col-12 mb-3">
                {{form.description.label_tag}}
                {{form.description}}
                <p>{% if form.description.help_text %}{{form.description.help_text}}{% endif %}</p>
                {% if form.description.errors %}
                    {% for error in form.description.errors %}
                        <div class="alert alert-danger">
                            {{error}}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            
            <div class="col-6 mb-3">
                {% if form.cover %}
                    <a href="{{events.cover.url}}"><img src="{{events.cover.url}}" class='img-fluid' width="100" height="100"></a>
                {% endif %}
                {{form.cover.label_tag}}
                {{form.cover}}
                <p>{% if form.cover.help_text %}{{form.cover.help_text}}{% endif %}</p>
                {% if form.cover.errors %}
                    {% for error in form.cover.errors %}
                        <div class="alert alert-danger">
                            {{error}}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="col-6 mb-3">
                {{form.cover_caption.label_tag}}
                {{form.cover_caption}}
                <p>{% if form.cover_caption.help_text %}{{form.cover_caption.help_text}}{% endif %}</p>
                {% if form.cover_caption.errors %}
                    {% for error in form.cover_caption.errors %}
                        <div class="alert alert-danger">
                            {{error}}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="col-12 mb-3">
                {% if events.images %}
                    <div class="d-flex flex-row flex-wrap justify-content-center gap-1">
                        {% for image in events.images.all %}
                            <div class="d-flex flex-column justify-content-center border">
                                <a href="{{image.image.url}}"><img src="{{image.image.url}}" class='img-fluid shadow-sm' width="100" height="100"></a>
                                <a role="button" href="{% url "blog:delete_image_event" image.id %}" class="link btn btn-sm btn-outline-secondary text-body-secondary mx-auto">Excluir</a>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                {{form_images.image.label_tag}}
                {{form_images.image}}
                <p>{% if form_images.image.help_text %}{{form_images.image.help_text}}{% endif %}</p>
                {% if form_images.image.errors %}
                    {% for error in form_images.image.errors %}
                        <div class="alert alert-danger">
                            {{error}}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <button type="submit" class="btn btn-outline-primary">Salvar</button>
        </form>
    </div>
{% endblock admin_content %}

project/blog/templates/blog/pages/edit_post.html
{% extends "blog/pages/admin_dashboard.html" %}
{% block admin_content %}
    {% include "blog/partials/_edit_post.html" %}
{% endblock admin_content %}

project/blog/templates/blog/pages/events.html
{% extends "blog/pages/admin_dashboard.html" %}
{% block admin_content %}
    {% include "blog/partials/table_events.html" %}
{% endblock admin_content %}

project/blog/templates/blog/pages/login.html
{% extends "blog/base.html" %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static "blog/css/sign-in.css" %}">{% endblock style %}
{% block content %}
    {% if user.is_authenticated is not True %}
        <main class="form-signin w-100 m-auto">
            <form class="border border-sm shadow p-4" method="post">
                {% csrf_token %}
                {% if site_setup.logo %}
                    <img class="mb-4" src="{{site_setup.logo.url}}" alt="" width="72" height="57">
                    <span class="fs-2 fw-bold text-shadow-sm text-black">{{site_setup.title}}</span>
                {% else %}
                    <span class="fs-2 fw-bold text-shadow-sm text-black">{{site_setup.title}}</span>
                {% endif %}        
                <h1 class="h3 my-3 fw-normal">Faça o login por favor</h1>

                <div class="form-floating">
                    {{form.username}}
                    {% if form.username.errors %}
                        <div class="alert alert-danger">
                            {% for error in form.username.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <label for="floatingInput">Usuário</label>
                </div>
                <div class="form-floating">
                    {{form.password}}
                    {% if form.password.errors %}
                        <div class="alert alert-danger">
                            {% for error in form.password.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <label for="floatingPassword">Senha</label>
                </div>
            
                <div class="form-check text-start my-3">
                    <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                    Lembrar
                    </label>
                </div>
                <button class="btn btn-primary w-100 py-2" type="submit">Entrar</button>
                <p class="mt-5 mb-3 text-body-secondary">&copy; {% now "Y" %}</p>
            </form>
            {% if form.non_field_errors %}
                <div class="alert alert-danger mt-3">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </main>
    {% else %}
        <main class="flex-shrink-0">
            <div class="container container-width text-center">
                <h1 class="mt-5">Olá, você ja está logado {{user.first_name}} !</h1>
                <p class="lead">Já está habilitado para interagir com as novidades e eventos do {{site_setup.title}}.</p>
                <p>Ou se desejar, clique <a href="{% url "blog:logout" %}">aqui</a> para sair de sua conta.</p>
            </div>
            <hr class="text-primary m-5">
        </main>
    {% endif %}
{% endblock content %}

project/blog/templates/blog/pages/new_category.html
{% extends "blog/pages/admin_dashboard.html" %}
{% block admin_content %}
    <div class="conatiner container-width mx-auto">
        
        <form class="row align-items-center" method="POST">
            {% csrf_token %}
            <div class="col-6 mb-3">
                {{form.name.label_tag}}
                {{form.name}}
                <p>{% if form.name.help_text %}{{form.name.help_text}}{% endif %}</p>
            </div>
            <div class="col-6 mb-3">
                <button type="submit" class="btn btn-outline-primary">Adicionar</button>
            </div>
        </form>

        <h2>Dados</h2>
        <div class="d-flex justify-content-center">
            {% include "blog/partials/_pagination.html" %}
        </div>
        <div class="table-responsive small">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Categoria</th>
                        <th scope="col">Opções</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in page_obj %}
                        <tr>
                            <td>{{item.id}}</td>
                            <td>{{item.name}}</td>
                            <td>
                                <a role="button" class="link text-decoration-none text-body-secondary mx-1" data-bs-toggle="modal" data-bs-target="#{{item.id}}"><i class="fa-solid fa-trash"></i></a>
                            </td>
                        </tr>
                        {% comment %} MODAL DE EXCLUSÃO {% endcomment %}
                        <div class="modal fade p-4 py-md-5" tabindex="-1" role="dialog" id="{{item.id}}">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content rounded-3 shadow">
                                    <div class="modal-body p-4 text-center">
                                        <h5 class="mb-0">Deseja realmente excluir?</h5>
                                        <p class="mb-0">Ao excluir este registro não será mais possível recuperá-lo.</p>
                                    </div>
                                    <div class="modal-footer flex-nowrap p-0">
                                        <form method="POST">
                                            <a type="submit" role="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end" href="{% url "blog:delete_category" item.id %}"><strong>Sim, continuar</strong></a>
                                        </form>
                                        <button type="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0" data-bs-dismiss="modal">Não, cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock admin_content %}

project/blog/templates/blog/pages/shops.html
{% extends "blog/base.html" %}
{% block content %}
    {% include "blog/partials/_posts.html" %}
{% endblock content %}