project/blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
from site_setup.views import site_config

app_name = 'blog'

urlpatterns = [

    path('', views.index, name="index"),
    path('admin_dashboard/', views.admin_dashboard, name="admin_dashboard"),

    path('site_config', site_config, name="site_config"),

    path('users/', views.users_views, name="users"),
    path('create_user/', views.create_user, name="create_user"),
    path('edit_user/<int:user_id>/', views.edit_user, name="edit_user"),
    path('change_password/<int:user_id>/', views.change_password, name="change_password"),
    path('user_active/<int:user_id>/', views.user_active, name="user_active"),
    path('user_staff/<int:user_id>/', views.user_staff, name="user_staff"),
    path('delete_user/<int:user_id>/', views.delete_user, name="delete_user"),

    path('news/', views.news, name="news"),
    path('new/<slug:slug>/', views.new, name="new"),
    path('add_news/', views.add_news, name="add_news"),
    path('edit_news/<int:id>/', views.edit_news, name="edit_news"),
    path('delete_news/<int:id>/', views.delete_news, name="delete_news"), # type: ignore
    path('delete_image_news/<int:id>/', views.delete_image_news, name="delete_image_news"),
    path('news_published/<int:id>/', views.news_published, name="news_published"),

    path('events/', views.events, name='events'),
    path('event/<slug:slug>/', views.event, name="event"),
    path('add_event/', views.add_event, name="add_event"),
    path('edit_event/<int:id>/', views.edit_event, name="edit_event"),
    path('delete_event/<int:id>/', views.delete_event, name="delete_event"),
    path('delete_image_event/<int:id>/', views.delete_image_event, name="delete_image_event"),
    path('event_published/<int:id>/', views.event_published, name="event_published"),

    path('page/<slug:slug>/', views.page, name="page"),

    path('search/', views.search, name='search'),

    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    
    path('post/<slug:slug>/', views.post, name="post"), 
    path('category/<slug:slug>/', views.category, name="category"),
    path('tag/<slug:slug>/', views.tag, name="tag"),
    path('shops/', views.shops, name='shops'),
    # path('shops/', views.ShopsViews.as_view(), name='shops'),
    path('admin_shops/', views.admin_shops, name='admin_shops'),
    path('new_post/', views.new_post, name='new_post'),
    path('edit_post/<int:id>/', views.edit_post, name="edit_post"),
    path('delete_post/<int:id>/', views.delete_post, name="delete_post"),
    path('delete_image_post/<int:id>/', views.delete_image_post, name="delete_image_post"),
    path('shop_published/<int:id>/', views.shop_published, name="shop_published"),
    path('new_category/', views.new_category, name='new_category'),
    path('new_tag/', views.new_tag, name='new_tag'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('delete_tag/<int:tag_id>/', views.delete_tag, name='delete_tag'),

    path('newsletters/', views.subs, name="newsletters"),
    path('newsletter/', views.newsletter, name="newsletter"), # type: ignore
    path('delete_newsletter/<int:newsletter_id>/', views.delete_newsletter, name="delete_newsletter"),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/site_setup/models.py
from django.db import models
from utils.model_validators import validate_png
from utils.images import resize_image, resize_image_slide, resize_image_logo

class MenuLink(models.Model):
    class Meta:
        verbose_name = 'Menu Link'
        verbose_name_plural = 'Menu Links'

    text = models.CharField(max_length=50)
    url_or_path = models.CharField(max_length=2048)
    new_tab = models.BooleanField(default=False)

    site_setup = models.ForeignKey('SiteSetup', on_delete=models.CASCADE, blank=True, null=True, default=None)

    def __str__(self):
        return self.text
    
class SiteSetup(models.Model):
    class Meta:
        verbose_name = 'Setup'
        verbose_name_plural = 'Setup'
    
    # TITLE SITE
    show_title = models.BooleanField(default=True)
    title = models.CharField(max_length=65)

    # DESCRIPTION / SLOGAN
    show_description = models.BooleanField(default=True)
    description = models.CharField(max_length=255, blank=True, null=True)

    # LOGO SITE
    show_logo = models.BooleanField(default=True)
    logo = models.ImageField(upload_to='assets/logo/%Y/%m/%d/', blank=True, null=True, validators=[validate_png])

    # BANNER WELCOME
    show_welcome_banner = models.BooleanField(default=True)
    title_welcome_banner = models.CharField(max_length=65, blank=True, null=True)
    welcome_banner = models.TextField(blank=True, null=True)

    # BANNER BESTS
    show_best_banner = models.BooleanField(default=True)
    title_best_banner = models.CharField(max_length=255, blank=True, null=True)
    best_banner = models.TextField(blank=True, null=True)
    link_best_banner = models.CharField(max_length=255, blank=True, null=True)

    # BANNER HISTORY
    show_history_banner = models.BooleanField(default=True)
    title_history_banner = models.CharField(max_length=255, blank=True, null=True)
    history_banner = models.TextField(blank=True, null=True)
    link_history_banner = models.CharField(max_length=255, blank=True, null=True)
    img_history = models.ImageField(upload_to='assets/img_history/%Y/%m/%d', blank=True, null=True)

    # FOOTER OPERATING TIME
    show_operate_shop = models.BooleanField(default=True)
    operate_time_shop = models.TextField(blank=True, null=True)
    show_operate_food = models.BooleanField(default=True)
    operate_time_food = models.TextField(blank=True, null=True)

    # MAPS LOCATION
    show_location = models.BooleanField(default=True)
    endereco = models.CharField(max_length=255, blank=True, null=True)
    numero = models.CharField(max_length=255, blank=True, null=True)
    bairro = models.CharField(max_length=255, blank=True, null=True)
    cidade_estado = models.CharField(max_length=255, blank=True, null=True)
    cep = models.CharField(max_length=255, blank=True, null=True)

    # SOCIAL MEDIAS
    show_social = models.BooleanField(default=True)
    facebook = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    x_twitter = models.URLField(blank=True, null=True)
    youtube = models.URLField(blank=True, null=True)

    # ALL SETUPS
    show_login = models.BooleanField(default=True)
    show_header = models.BooleanField(default=True)
    show_footer = models.BooleanField(default=True)
    show_search = models.BooleanField(default=True)
    show_menu = models.BooleanField(default=True)
    show_pagination = models.BooleanField(default=True)
    show_subscribe = models.BooleanField(default=True)
    show_comments = models.BooleanField(default=True)
    show_news = models.BooleanField(default=True)
    show_events = models.BooleanField(default=True)

    # CAROUSEL SLIDES
    show_carousel = models.BooleanField(default=True)
    slide1 = models.ImageField(upload_to='assets/slides/%Y/%m/%d/', blank=True, default='', validators=[validate_png])
    slide1_title = models.CharField(max_length=65, blank=True, null=True)
    slide1_description = models.CharField(max_length=255, blank=True, null=True)

    slide2 = models.ImageField(upload_to='assets/slides/%Y/%m/%d/', blank=True, default='', validators=[validate_png])
    slide2_title = models.CharField(max_length=65, blank=True, null=True)
    slide2_description = models.CharField(max_length=255, blank=True, null=True)

    slide3 = models.ImageField(upload_to='assets/slides/%Y/%m/%d/', blank=True, default='', validators=[validate_png])
    slide3_title = models.CharField(max_length=65, blank=True, null=True)
    slide3_description = models.CharField(max_length=255, blank=True, null=True)

    favicon = models.ImageField(upload_to='assets/favicon/%Y/%m/%d/', blank=True, default='', validators=[validate_png])

    def save(self, *args, **kwargs):
        current_logo_name =  str(self.logo.name)
        current_img_history_name =  str(self.img_history.name)
        current_favicon_name =  str(self.favicon.name)
        current_slide1_name = str(self.slide1.name)
        current_slide2_name = str(self.slide2.name)
        current_slide3_name = str(self.slide3.name)
        super().save(*args, **kwargs)
        logo_changed = False
        img_history_changed = False
        favicon_changed = False
        slide1_changed = False
        slide2_changed = False
        slide3_changed = False

        if self.slide1:
            slide1_changed = current_slide1_name != self.slide1.name

        if self.slide2:
            slide2_changed = current_slide2_name != self.slide2.name

        if self.slide3:
            slide3_changed = current_slide3_name != self.slide3.name

        if self.favicon:
            favicon_changed = current_favicon_name != self.favicon.name
        
        if self.logo:
            logo_changed = current_logo_name != self.logo.name

        if self.img_history:
            img_history_changed = current_img_history_name != self.img_history.name

        if logo_changed:
            resize_image_logo(self.logo, 100)

        if favicon_changed:
            resize_image(self.favicon, 32)
        
        if slide1_changed:
            resize_image_slide(self.slide1)

        if slide2_changed:
            resize_image_slide(self.slide2)

        if slide3_changed:
            resize_image_slide(self.slide3)

        if img_history_changed:
            resize_image(self.img_history, 320)

    def __str__(self):
        return self.title

project/blog/views/_users_views.py
from django.shortcuts import render
from django.contrib.auth.models import User

def users_views(request):
    users = User.objects.order_by('first_name')

    context = {
        'users': users,
    }

    return render(request, 'blog/pages/users.html', context)

project/blog/views/admin_views.py
from django.shortcuts import render, redirect
from blog.models import User, CommentsEvents, CommentsNews, NewsLetter

def admin_dashboard(request):
    new_users = User.objects.order_by('-id')[:5]
    new_comments = CommentsNews.objects.order_by('-created_at')[:5]
    event_comments = CommentsEvents.objects.order_by('-created_at')[:5]
    news_letters = NewsLetter.objects.order_by('-id')[:5]

    context = {
        'new_users': new_users,
        'new_comments': new_comments,
        'event_comments': event_comments,
        'news_letters': news_letters,
    }

    return render(request, 'blog/partials/_main_dashboard.html', context)

project/blog/views/category_view.py
from django.shortcuts import render
from blog.models import Post
from django.core.paginator import Paginator

PER_PAGE = 9

def category(request, slug):
    shops = Post.objects.get_published().filter(category__slug=slug).order_by('id') # type: ignore
    
    if shops:
        for i in shops:
            category = f'{i.category.name} - '
    else:
        category = ''

    paginator = Paginator(shops, PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'shops': page_obj,
        'page_title': category,
    }

    return render(request, 'blog/pages/shops.html', context)

project/blog/views/change_password_view.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from blog.forms import CustomPasswordChangeForm
from django.contrib.auth.decorators import login_required

def is_admin(user):
    return user.is_superuser

@login_required
def change_password(request, user_id):

    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        form = CustomPasswordChangeForm(user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Senha atualizada com sucesso!')
            return redirect('blog:change_password', user_id=user_id)
        else:
            print(form.errors)
            messages.error(request, 'Algo deu errado ao alterar sua senha, verifique os campos e tente novamente.')
    else:
        form = CustomPasswordChangeForm(user)

    context = {
        'form': form,
    }

    return render(request, 'blog/pages/change_password.html', context)

project/blog/views/create_user_view.py
from django.shortcuts import render, redirect
from django.contrib import messages
from blog.forms import CustomUserCreationForm, ProfileUpdateForm
from blog.models import Profile
from django.contrib.auth.decorators import login_required, user_passes_test

def is_admin(user):
    return user.is_superuser

def create_user(request):

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        form_image = ProfileUpdateForm(request.POST, request.FILES)

        if form.is_valid():
            new_user = form.save()

            if form_image.is_valid():
                image = request.FILES.get('profile_image')
                Profile.objects.create(user=new_user, profile_image=image)
                messages.success(request, 'Imagem de perfil salva com sucesso')

            messages.success(request, 'Usuário criado com sucesso!')
            return redirect('blog:index')
        else:
            messages.error(request, 'Algo deu errado, verifique os campos necessários!')

    else:
        form = CustomUserCreationForm()
        form_image = ProfileUpdateForm()

    context = {
        'form': form,
        'form_image': form_image,
    }

    return render(request, 'blog/pages/create_user.html', context)

project/blog/views/edit_user_view.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from blog.forms import CustomUserChangeForm, ProfileUpdateForm
from blog.models import Profile
from django.contrib.auth.decorators import login_required, user_passes_test

def is_admin(user):
    return user.is_superuser

@login_required
def edit_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    profile, created = Profile.objects.get_or_create(user=user)

    form = CustomUserChangeForm(instance=user)
    form_image = ProfileUpdateForm(instance=profile)


    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)
        form_image = ProfileUpdateForm(request.POST, request.FILES, instance=profile)

        # if form.is_valid():
        #     new_user = form.save()

        #     if form_image.is_valid():
        #         new_user.profile_image.profile_image.delete()
        #         image_instance = request.FILES.get('profile_image')
        #         Profile.objects.create(user=new_user, profile_image=image_instance)

            # if form_image.is_valid():
                # image_instance = form_image.save(commit=False)
                # image_instance.user = new_user
                # print(image_instance.user)
                # image_instance.save()

                # if image_instance:
                # messages.success(request, 'Imagem atualizada com sucesso!')

        if form.is_valid() and form_image.is_valid():
            form.save()
            form_image.save()

            if form_image:
                messages.success(request, 'Imagem atualizada com sucesso!')

            messages.success(request, 'Usuário atualizado com sucesso!')
            return redirect('blog:edit_user', user_id=user_id)
        else:
            messages.error(request, 'Algo deu errado ao atualizar seus dados, verifique os campos novamente.')        

    context = {
        'profile': user,
        'form': form,
        'form_image': form_image,
    }

    return render(request, 'blog/pages/edit_user.html', context)

def user_active(request, user_id):
    activated = User.objects.get(id=user_id)

    if request.POST.get('is_active') == 'on':
        activated.is_active = True
        activated.save()
        messages.success(request, 'Usúário ativado')
        return redirect('blog:users')
    else:
        activated.is_active = False
        activated.save()
        messages.error(request, 'Usuário desativado')
        return redirect('blog:users')
    
def user_staff(request, user_id):
    activated = User.objects.get(id=user_id)

    if request.POST.get('is_staff') == 'on':
        activated.is_staff = True
        activated.save()
        messages.success(request, 'Usúário com acesso administrativo')
        return redirect('blog:users')
    else:
        activated.is_staff = False
        activated.save()
        messages.error(request, 'Usuário sem acesso administrativo')
        return redirect('blog:users')
    
def delete_user(request, user_id):
    target = User.objects.get(id=user_id)

    if target:
        target.delete()
        messages.success(request, 'Usuário deletado com sucesso.')
        
    return redirect('blog:users')

project/blog/templates/blog/partials/_header.html
{% if site_setup.show_header %}
{% load static %}
    <header class="py-4 mb-5 border-bottom bg-header">
        <div class="container">
            <div class="container d-flex flex-wrap justify-content-center mb-sm-4">
                <a href="/" class="d-flex flex-column align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none">
                    {% if site_setup.show_logo %}
                        <div>
                            {% if site_setup.logo %}
                                <img src="{{site_setup.logo.url}}" class="d-block mx-lg-auto img-fluid" alt="{{site_setup.title}}" loading="lazy">
                            {% else %}
                                <img src="{% static "blog/img/ops.png" %}" class="d-block mx-lg-auto img-fluid" width="100" height="50" alt="OPS !" loading="lazy">
                            {% endif %}
                        </div>
                    {% endif %}
                    <span class="fs-1 fw-bold text-shadow-sm text-white">{{site_setup.title}}</span>
                    <span class="fs-4 fst-italic text-white">{{site_setup.description|safe}}</span>
                </a>
                {% if site_setup.show_search %}
                    <form class="col-12 col-lg-auto mb-3 mb-lg-0" role="search" action="{% url "blog:search" %}" method="GET">
                        <input id="search-all" name="search-all" type="search" class="form-control" placeholder="Pesquisar lojas ..." aria-label="Search" value="{{search_value}}">
                    </form>
                {% endif %}
            </div>
        </div>
        <nav class="py-3 border-top border-bottom bg-nav shadow">
            <div class="container d-flex flex-wrap">
                {% if site_setup.show_menu %}
                    <ul class="nav me-auto">
                        {% for link in site_setup.menulink_set.all %}
                            <li class="nav-item">
                                {% if link.new_tab %}
                                    <a target="_blank" href="{{link.url_or_path}}" class="link fs-4 px-2">{{link.text}}</a>
                                {% else %}
                                    <a href="{{link.url_or_path}}" class="link fs-4 px-2">{{link.text}}</a>
                                {% endif %}
                            </li>
                        {% endfor %}
                        <li class="nav-item">
                            <a class="link fs-4 px-2 dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">Lojas</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url "blog:shops" %}">Todas</a></li>
                                {% for category in category %}
                                    <li><a class="dropdown-item" href="{% url "blog:category" category.slug %}">{{category.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                {% endif %}
                {% if site_setup.show_login %}
                    {% if user.is_authenticated is not True %}
                        <ul class="nav">
                            <li class="nav-item my-auto"><i class="text-white fa-regular fa-user fs-5 px-2"></i></li>
                            <li class="nav-item"><a href="{% url "blog:login" %}" class="link fs-4 px-2">Entrar</a></li>
                            <div class="vr text-light mx-2"></div>
                            <li class="nav-item"><a href="{% url "blog:create_user" %}" class="link fs-4 px-2">Registrar</a></li>
                        </ul>
                    {% else %}
                        <ul class="nav">
                            {% if user.profile_image.profile_image %}
                                <a href="{{ user.profile_image.profile_image.url }}">
                                    <img src="{{ user.profile_image.profile_image.url }}" alt="{{ user.username }}'s profile picture" width="20" height="20" class="img-fluid shadow rounded-circle m-2">
                                </a>
                            {% else %}
                                <li class="nav-item my-auto"><i class="text-white fa-regular fa-user fs-5 px-2"></i></li>
                            {% endif %}
                            <li class="nav-item d-flex align-items-center">
                                <a class="link fs-4 px-2 dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">Minha Conta</a>
                                <ul class="dropdown-menu">
                                    {% if user.is_staff and user.is_authenticated %}
                                        <li><a class="dropdown-item" href="{% url "blog:admin_dashboard" %}">Administração</a></li>
                                    {% endif %}
                                    <li><a class="dropdown-item" href="{% url "blog:edit_user" user.id %}">Dados Pessoais</a></li>
                                    <li><a class="dropdown-item" href="{% url "blog:change_password" user.id %}">Alterar Senha</a></li>
                                    <li><a class="dropdown-item" href="{% url "blog:logout" %}">Sair</a></li>
                                </ul>
                            </li>
                        </ul>
                    {% endif %}
                {% endif %}
            </div>
        </nav>
    </header>
    {% include "blog/partials/_messages.html" %}
{% endif %}

project/blog/templates/blog/partials/_news.html
{% load static %}
{% if site_setup.show_news %}
    <div class="container px-4 py-5 shadow" id="custom-cards">
        <h2 class="pb-2 border-bottom bg-dark-blue text-white p-2">ÚLTIMAS NOVIDADES</h2>
        {% if news %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4 mt-4">
                {% for new in news %}
                    <div class="col">
                        <div class="card h-100 shadow">
                            <a href="{% url "blog:new" new.slug %}"  class="text-decoration-none h-100">
                                <img src="{{ new.cover.url }}" class="h-100 img-fluid rounded-top" alt="{{new.cover_caption}}">
                            </a>
                            <div class="card-body d-flex flex-row justify-content-between">
                                <div>
                                    <h5 class="card-title">{{new.title}}</h5>
                                    <p class="card-text">{{new.short_description}}</p>
                                </div>
                                <div>
                                    <i class="fa-regular fa-newspaper fs-2"></i>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="d-flex justify-content-center">
                                    <a href="{% url "blog:new" new.slug %}" class="text-decoration-none fs-4"><em>Saiba mais ...</em></a>
                                </div>
                                <hr>
                                <ul class="d-flex justify-content-between list-unstyled mb-0 mt-auto">
                                    <li class="d-flex align-items-center me-3">
                                        <a href="{% url "blog:new" new.slug %}">
                                            <small class="mx-2 btn btn-sm btn-outline-secondary position-relative">
                                                <i class="fa-regular fa-comment"></i>
                                                Comentários
                                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-primary">
                                                    {{new.num_comments}}
                                                    <span class="visually-hidden">{{new.num_comments}}</span>
                                                </span>
                                            </small>
                                        </a>
                                    </li>
                                    <li class="d-flex align-items-center">
                                        <small>Criado em: {{new.created_at}}</small>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% else %}
    <h1 class="bg-danger text-white text-center">Sem Novidades !</h1>
{% endif %}

project/blog/templates/blog/partials/_page.html
<h1 class="w-50 text-center bg-secondary-subtle rounded mx-auto p-2">{{pages.title}}</h1>

<div class="container mb-4 p-5 mx-auto shadow rounded">
    {{pages.content|safe}}
</div>

project/blog/templates/blog/partials/_scripts.html
{% load static %}
<script src="{% static 'blog/js/bootstrap.bundle.min.js' %}"></script>

project/blog/templates/blog/partials/_shops.html
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static "blog/css/modal.css" %}">{% endblock style %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <div class="d-flex flex-row flex-wrap, align-items-center gap-3">
        <h1 class="h2">LOJAS</h1>
        <a class="btn btn-sm btn-outline-secondary d-flex align-items-center gap-1" aria-current="page" href="{% url "blog:new_post" %}">
            <i class="fa-regular fa-plus"></i>
            Nova loja
        </a>
        <a class="btn btn-sm btn-outline-secondary d-flex align-items-center gap-1" aria-current="page" href="{% url "blog:new_category" %}">
            <i class="fa-regular fa-plus"></i>
            Nova categoria
        </a>
        <a class="btn btn-sm btn-outline-secondary d-flex align-items-center gap-1" aria-current="page" href="{% url "blog:new_tag" %}">
            <i class="fa-regular fa-plus"></i>
            Novas tags
        </a>
    </div>
   
    <div class="btn-toolbar mb-2 mb-md-0">
        <a role="button" class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-regular fa-calendar"></i>Filtrar por data
        </a>
    </div>
</div>

<h2>Dados</h2>
<div class="d-flex justify-content-center">
    {% include "blog/partials/_pagination.html" %}
</div>
<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Número</th>
                <th scope="col">Link</th>
                <th scope="col">Criada em</th>
                <th scope="col">Categoria</th>
                <th scope="col">Publicado</th>
                <th scope="col">Opções</th>
            </tr>
        </thead>
        <tbody>
            {% for loja in page_obj %}
                <tr>
                    <td>{{loja.title}}</td>
                    <td>{{loja.number}}</td>
                    <td>{{loja.get_absolute_url}}</td>
                    <td>{{loja.created_at}}</td>
                    <td>{{loja.category|default_if_none:"Sem categoria"}}</td>
                    <td>                        
                        <form method="POST" action="{% url 'blog:shop_published' loja.id %}">
                            {% csrf_token %}
                            <div> 
                                {% if loja.is_published %}
                                    <button type="submit" class="btn btn-sm btn-link text-success link"><i class="fa-solid fa-circle-check"></i></button>
                                    <input class="visually-hidden" type="checkbox" id="flexSwitchCheckChecked{{ loja.id }}" name="is_published">
                                {% else %}
                                    <button type="submit" class="btn btn-sm btn-link text-danger link"><i class="fa-solid fa-circle-xmark"></i></button>
                                    <input class="visually-hidden" type="checkbox" id="flexSwitchCheckChecked{{ loja.id }}" name="is_published" checked>
                                {% endif %}
                            </div>
                        </form>
                    </td>
                    <td>
                        <a role="button" class="link text-decoration-none text-body-secondary mx-1" href="{% url "blog:edit_post" loja.id %}"><i class="fa-solid fa-pen"></i></a>
                        <a role="button" class="link text-decoration-none text-body-secondary mx-1" data-bs-toggle="modal" data-bs-target="#{{loja.id}}"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
                {% comment %} MODAL DE EXCLUSÃO {% endcomment %}
                <div class="modal fade p-4 py-md-5" tabindex="-1" role="dialog" id="{{loja.id}}">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content rounded-3 shadow">
                            <div class="modal-body p-4 text-center">
                                <h5 class="mb-0">Deseja realmente excluir?</h5>
                                <p class="mb-0">Ao excluir este registro não será mais possível recuperá-lo.</p>
                            </div>
                            <div class="modal-footer flex-nowrap p-0">
                                <form method="POST">
                                    <a type="submit" role="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end" href="{% url "blog:delete_post" loja.id %}"><strong>Sim, continuar</strong></a>
                                </form>
                                <button type="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0" data-bs-dismiss="modal">Não, cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </tbody>
    </table>
</div>